CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name       VARCHAR(50)              NOT NULL,
    hashed_password VARCHAR(255)             NOT NULL,
    version         BIGINT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_users_user_name UNIQUE (user_name)
);

CREATE TABLE roles (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL,
    user_id   BIGINT      NOT NULL,
    CONSTRAINT fk_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_roles_user_id ON roles (user_id);
