-- Turns per-user role rows (roles.user_id + role_code) into shared role reference data joined through user_roles.
-- Tables are recreated rather than renamed so the old constraint/index names cannot clash on either database.

CREATE TABLE user_role_codes_tmp AS SELECT DISTINCT user_id, role_code FROM roles;

DROP TABLE roles;

CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    CONSTRAINT uk_roles_code UNIQUE (code)
);

INSERT INTO roles (code) VALUES ('ADMINISTRATOR');
INSERT INTO roles (code) VALUES ('EDITOR');
INSERT INTO roles (code)
SELECT DISTINCT t.role_code FROM user_role_codes_tmp t
WHERE NOT EXISTS (SELECT 1 FROM roles r WHERE r.code = t.role_code);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);

INSERT INTO user_roles (user_id, role_id)
SELECT t.user_id, r.id FROM user_role_codes_tmp t JOIN roles r ON r.code = t.role_code;

DROP TABLE user_role_codes_tmp;
